### ISSUE TITLE
Add 6Workstation, 7Workstation and 7.1 $releasever symlinks

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt-pack#10]
[Documentation for RHEL systems](https://docs.saltstack.com/en/develop/topics/installation/rhel.html#installation-rhel-repo) says to use the following URL for the salt repo https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest but there is no link for 6 and 7 Workstation machines. It would be nice if a symlink can be added to point to https://repo.saltstack.com/yum/redhat/(6|7)/$basearch/latest so workstation installs will work without needing to manually specify the version in the .repo file.

The default variables are 6Workstation and 7Workstation. It may also be useful to point out that some users (including me) use the point release for the $releasever variable. This means our 7.1 servers have $releasever set to 7.1 and not 7Server.

*Copied from https://github.com/saltstack/salt/issues/30315.*

**Comment by dmurphy18** [comment]
Is there a need for 5Workstation ?

**Comment by dmurphy18** [comment]
Added to staging area for repo, should be available with the next point release

**Comment by dmurphy18** [comment]
Also added [7|6|5]Client and [7|6|ComputeNode similar to  http://ftp.redhat.com/pub/redhat/linux/enterprise/

**Comment by rothgar** [comment]
@dmurphy18 good thinking. I also use computenode so that would be helpful too.
