### ISSUE TITLE
update zeromq in your repo

### ISSUE THREAD

**Issue by carlwgeorge** [saltstack/salt-pack#117]
EPEL7 recently had a [major update of zeromq](https://bugzilla.redhat.com/show_bug.cgi?id=1301163) that bumped the library soname from `libzmq.so.4()` to `libzmq.so.5()`.  EPEL packages that need that that library have already been rebuilt.  Unfortunately, this now means that using the salt repo and EPEL on EL7 results in errors when trying to run a simple `yum update`.

<details>
```
# yum update
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repo1.ash.innoscale.net
 * epel: fedora-epel.mirror.lstn.net
 * extras: repo1.ash.innoscale.net
 * updates: repo1.ash.innoscale.net
Resolving Dependencies
--> Running transaction check
---> Package zeromq.x86_64 0:4.0.5-4.el7 will be updated
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.7.0-1.el7.x86_64
---> Package zeromq.x86_64 0:4.1.4-5.el7 will be an update
--> Processing Dependency: libsodium.so.13()(64bit) for package: zeromq-4.1.4-5.el7.x86_64
--> Running transaction check
---> Package libsodium.x86_64 0:1.0.5-1.el7 will be installed
---> Package zeromq.x86_64 0:4.0.5-4.el7 will be updated
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.7.0-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: python-zmq-14.7.0-1.el7.x86_64 (@salt-2015.8)
           Requires: libzmq.so.4()(64bit)
           Removing: zeromq-4.0.5-4.el7.x86_64 (@epel)
               libzmq.so.4()(64bit)
           Updated By: zeromq-4.1.4-5.el7.x86_64 (epel)
              ~libzmq.so.5()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
</details>

Yum is trying to update zeromq from the salt repo version to the newer EPEL version, but cannot proceed due to the fact that the salt python-zmq package was built against the older zeromq, and thus has a direct dependency on `libzmq.so.4()`.  I have worked around this error temporarily by adding `exclude=zeromq*` to my EPEL repo configuration.

I am seeing the error using the 'salt-2015.8' repo, but it should be reproducible on all of the salt repos since it appears they all have the same version of zeromq.

To fix this permanently for everyone, please update the salt repo zeromq package to at least version 4.1.4-5, and rebuild the python-zmq package to correctly relink against the library soname.

**Comment by dmurphy18** [comment]
Fixing with salt-pack https://github.com/saltstack/salt-pack/issues/118
