### ISSUE TITLE
add minimum documentation

### ISSUE THREAD

**Issue by bbinet** [saltstack/salt-pack#13]
Would it be possible to add minimum documentation to the readme to explain how to use salt-pack to generate the salt packages?

**Comment by dmurphy18** [comment]
Awaiting Jacob's review

**Comment by beardedeagle** [comment]
Any headway on this?

**Comment by dmurphy18** [comment]
@bbinet @beardedeagle It is under active review by documentation, having to re-arrange my writing and adjusting for style.  I hope that I should have it up on salt-pack soon.

**Comment by bbinet** [comment]
@dmurphy18 Great, thanks!

**Comment by dmurphy18** [comment]
@bbinet @beardedeagle The README.md is now up on the repo, Hence want to close this issue, unless their are any objections.  Noting I shall be updating it again soon for Ubuntu 16.04 being the default for Ubuntu, and some minor spelling/format mistakes.

**Comment by bbinet** [comment]
No objection from me, and thanks for the documentation.
