### ISSUE TITLE
pkgbuild.repo fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by jbfriedrich** [saltstack/salt-pack#132]
### Description of Issue/Question

I am trying to build my own packages with my own patch set of Salt 2016.3.2 on Ubuntu 16.04. So far so good, the packages are all build and work as intended. But when i try to build the repo via 

```
salt buildsalt state.sls repo.ubuntu.ubuntu16 pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604","gpg_passphrase":"my secret key password"}`
```

I get the following error message:

> ```
>       ID: /srv/pkgs/ubuntu1604/amd64
> Function: pkgbuild.repo
>   Result: False
>  Comment: An exception occurred in this state: Traceback (most recent call last):
>             File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
>               **cdata['kwargs'])
>             File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper
>               return f(*args, **kwargs)
>             File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 368, in repo
>               if res['retcode'] > 0:
>           TypeError: 'NoneType' object has no attribute '__getitem__'
>  Started: 21:19:44.928178
> Duration: 586004.209 ms
>  Changes:  
> ```

The minion log on the build VM shows the same error, but also that reprepo fails with a return code 251 for every deb package:

> ```
> [salt.loaded.int.module.cmdmod][ERROR   ][127742] Command 'reprepro --ignore=wrongdistribution --component=main -Vb . includedeb xenial /srv/pkgs/ubuntu1604/amd64/libsodium18_1.0.8-5_amd64.deb' failed with return code: 251
> ```

When I run it a second time, without deleting folder or packages first, I get the following error

> ```
> 2016-08-19 21:41:56,731 [salt.state       ][ERROR   ][128999] An exception occurred in this state: Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call **cdata['kwargs'])
> File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1651, in wrapper return f(*args, **kwargs)
> File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 366, in repo
> res = __salt__[func](name, keyid, env, use_passphrase, gnupghome, runas)
> File "/usr/lib/python2.7/dist-packages/salt/modules/debbuild.py", line 727, in make_repo
> 'Reprepro includedsc for codename {0} and file {1} failed with proc.status {2}'.format(codename, abs_file, proc_exitstatus)
> SaltInvocationError: Reprepro includedsc for codename xenial and file /srv/pkgs/ubuntu1604/amd64/timelib_0.2.4-1.dsc failed with proc.status 254
> ```
### Setup

I am using Ubuntu 16.04 on the salt-master and the salt-minion. Very basic VMs with a minimal installation of Ubuntu.
### Steps to Reproduce Issue
- Deploy your build VM
- Set up build VM via `salt buildsaltvm state.sls setup.ubuntu.ubuntu16 -l debug pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604"}'`
- Build packages via `salt buildsaltvm state.highstate -l debug pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604"}'`
- Create repo via `salt buildsaltvm state.sls repo.ubuntu.ubuntu16 -l debug pillar='{"build_version":"2016_3_2","build_release":"ubuntu1604","gpg_passphrase":"my secret password"}'` 
### Versions Report

> Salt Version:
>            Salt: 2016.3.2
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 2.4.2
>           gitdb: 0.6.4
>       gitpython: 1.0.1
>           ioflo: Not Installed
>          Jinja2: 2.8
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: 0.21.1
>            Mako: 1.0.3
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>          Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 15.2.0
>            RAET: Not Installed
>           smmap: 0.9.0
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.4
> 
> System Versions:
>            dist: Ubuntu 16.04 xenial
>         machine: x86_64
>         release: 4.4.0-31-generic
>          system: Linux
>         version: Ubuntu 16.04 xenial

**Comment by dmurphy18** [comment]
@jbfriedrich I believe you are missing the keyid field from the command:

 salt buildsaltvm state.sls repo.ubuntu.ubuntu16 -l debug pillar='{"build_version":"2016_3_2", "build_release":"ubuntu1604", **_"keyid":"id number" ,_** "gpg_passphrase":"my secret password"}'

the **_keyid_** number should be available from gpg --list-keys for the key you are using.

**Comment by jbfriedrich** [comment]
Hey @dmurphy18 . Sorry about the late reply. must be a copy and paste error. Even with putting the right keyid in, i still get the error while signing:

> 2016-09-26 21:54:35,799 [salt.utils.vt    ][DEBUG   ][129395] Child Forked! PID: 130385  STDOUT_FD: 30  STDERR_FD: 32
> 2016-09-26 21:54:35,800 [salt.utils.vt    ][DEBUG   ][129395] Terminal Command: /bin/sh -c reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/pkgs/ubuntu1604/amd64/ioflo_1.5.0-1.dsc
> 2016-09-26 21:54:37,505 [salt.utils.vt    ][DEBUG   ][129395] Child Forked! PID: 130408  STDOUT_FD: 30  STDERR_FD: 32
> 2016-09-26 21:54:37,506 [salt.utils.vt    ][DEBUG   ][129395] Terminal Command: /bin/sh -c reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/pkgs/ubuntu1604/amd64/python-tornado_4.2.1-2~ds+1.dsc
> 2016-09-26 21:54:39,209 [salt.loaded.int.module.cmdmod][INFO    ][129395] Executing command 'reprepro --ignore=wrongdistribution --component=main -Vb . includedeb xenial /srv/pkgs/ubuntu1604/amd64/libnacl-dev_20110221-4.1_amd64.deb' in directory '/srv/pkgs/ubuntu1604/amd64'
> 2016-09-26 21:54:39,210 [salt.loaded.int.module.cmdmod][DEBUG   ][129395] Running ['reprepro', '--ignore=wrongdistribution', '--component=main', '-Vb', '.', 'includedeb', 'xenial', '/srv/pkgs/ubuntu1604/amd64/libnacl-dev_20110221-4.1_amd64.deb'] in VT
> 2016-09-26 21:54:39,213 [salt.utils.vt    ][DEBUG   ][129395] Child Forked! PID: 130431  STDOUT_FD: 30  STDERR_FD: 32
> 2016-09-26 21:54:39,213 [salt.utils.vt    ][DEBUG   ][129395] Terminal Command: /bin/sh -c reprepro --ignore=wrongdistribution --component=main -Vb . includedeb xenial /srv/pkgs/ubuntu1604/amd64/libnacl-dev_20110221-4.1_amd64.deb
> 2016-09-26 21:54:39,715 [salt.utils.vt.Terminal.PID-130431.STDOUT][DEBUG   ][129395] Exporting indices...
> Successfully created './dists/xenial/Release.gpg.new'
> Successfully created './dists/xenial/InRelease.new'
> 2016-09-26 21:54:40,417 [salt.loaded.int.module.cmdmod][DEBUG   ][129395] output: Exporting indices...
> Successfully created './dists/xenial/Release.gpg.new'
> Successfully created './dists/xenial/InRelease.new'
> 
> 2016-09-26 21:54:40,420 [salt.utils.vt    ][DEBUG   ][129395] Child Forked! PID: 130452  STDOUT_FD: 30  STDERR_FD: 32
> 2016-09-26 21:54:40,421 [salt.utils.vt    ][DEBUG   ][129395] Terminal Command: /bin/sh -c reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
> 2016-09-26 21:54:42,153 [salt.loaded.int.module.cmdmod][INFO    ][129395] Executing command '/usr/lib/gnupg2/gpg-preset-passphrase --forget 1260B8AD713701AE3AAC81A391517245F44A3F33' as user 'root' in directory '/root'
> 2016-09-26 21:54:42,161 [salt.loaded.int.module.cmdmod][DEBUG   ][129395] output: 
> 2016-09-26 21:54:42,161 [salt.state       ][ERROR   ][129395] An exception occurred in this state: Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
>     **cdata['kwargs'])
>   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
>     return f(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 368, in repo
>     if res['retcode'] > 0:
> TypeError: 'NoneType' object has no attribute '__getitem__'

The output is from the minion debug log. If I do all the required steps manually, without salt being involved, it works fine. I am quite puzzled why this happens.

**Comment by dmurphy18** [comment]
@jbfriedrich Here are the commands I use to build Ubuntu16.04 

## Ubuntu 16.04
salt u16m state.sls setup.ubuntu.ubuntu16 pillar='{ "build_dest" : "/srv/ubuntu/2016.3.2/pkgs" }'
salt u16m state.sls pkg.salt.2016_3_2.ubuntu1604  pillar='{ "build_dest" : "/srv/ubuntu/2016_3_2/pkgs" , "build_version" : "2016_3_2" }'
salt u16m state.highstate pillar='{ "build_dest" : "/srv/ubuntu/2016.3.2/pkgs" , "build_version" : "2016_3_2" }'
salt u16m state.sls repo.ubuntu.ubuntu16  pillar='{ "build_dest" : "/srv/ubuntu/2016.3.2/pkgs", "keyid" : "DDDDDDDD" , "build_version" : "2016_3_2", "gpg_passphrase" : "fill-in here" }

KeyId and pgp_pasphase would be your own.

Other items to check is that the gpg agent is setup and working correctly after the setup command, for example: ps -ef| grep gpg should produce a process, gpg-agent --homedir /root/.gnupg --allow-preset-passphrase --max-cache-ttl 300 --daemon

Further check with 'gpg --fingerprint' after the setup command that the keys and names are setup correctly, that is, your public and private keys have been loaded correctly by the setup command.

On salt-master:
contents of salt-pack/pillar_roots is copied to /srv/pillar
contents of salt-pack/file_roots is copied to /srv/salt

in /srv/pillar/gpg_keys.sls should contain the armor exported versions of your own public and private keys (versions in salt-pack are examples, now expired)

I shall check that the README.txt for salt-pack is up to date, since there may be a step needing further explanation.  

Usually the problems I encountered with Ubuntu 16.04 building the repositories were due to the change to using gpg v2.1 and higher. The last command used before the error is using gpg--preset-passphrase which makes me suspect the issue is with gpg and your keys.

**Comment by jbfriedrich** [comment]
Thanks @dmurphy18! I will work through that and see if that helps me untangle the mess I made for myself. My current theory is that there is something wrong with the GPG agent or otherwise authentication as I can use the commands manually on the command line to create the repo. Will take me a couple of days though. Will bring back feedback as as I can.

**Comment by jbfriedrich** [comment]
@dmurphy18 I had the time already to go through everything. The gpg agent is started after setup is run. Also 'gpg --fingerprint' prints out the right key id:

![screen shot 2016-09-28 at 00 07 44](https://cloud.githubusercontent.com/assets/1968991/18896336/364ed896-8521-11e6-8cfd-19e4fd4a578e.jpg)

I used your lines states above as guidance. Here are mine in comparison:

> salt buildsalt state.sls setup.ubuntu.ubuntu16
> salt buildsalt state.sls pkg.salt.2016_3_3.ubuntu1604 pillar='{ "build_release" : "ubuntu1604" , "build_version" : "2016_3_3", "build_arch" : "amd64" }'
> salt buildsalt state.highstate pillar='{ "build_release" : "ubuntu1604" , "build_version" : "2016_3_3", "build_arch" : "amd64" }'
> salt buildsalt state.sls repo.ubuntu.ubuntu16 pillar='{ "keyid" : "XXXXF33", "build_release" : "ubuntu1604", "build_version" : "2016_3_3", "build_arch" : "amd64", "gpg_passphrase" : "my secret password" }' 

Still to no avail.

> 2016-09-28 02:02:28,474 [salt.loaded.int.module.cmdmod][DEBUG   ][129925] output: 
> 2016-09-28 02:02:28,475 [salt.state       ][ERROR   ][129925] An exception occurred in this state: Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
>     **cdata['kwargs'])
>   File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1652, in wrapper
>     return f(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 368, in repo
>     if res['retcode'] > 0:
> TypeError: 'NoneType' object has no attribute '__getitem__'

I still get the same error message. I still think you are right though, it must have something to do with gpg. Although I have no idea how to further debug this issue. It will take me a while to trace through the module to understand all the details, but this might be the only way. Any ideas? Suggestions?

**Comment by jbfriedrich** [comment]
Update: After a lot of testing I think that the issue is not gnupg or the gpg-agent

As stated above, the traceback shows that 'res' is a NoneType object, does not have an attribute 'getitem' and cannot check if the result is > 0. I will dig some more later today or tomorrow and take a closer look at 'pkgbuild.make_repo' and see if I can narrow it down even more. 

I looked at the change history and there were some changes made in a5f6630e977c9f4bbba450b82136672422aa5e2a to recognize command return codes. It is possbile that this broke compatibility for the signing in Debian/Ubuntu. If I comment out all the changes in pkgbuild.py and don't check for the return code, it works like a charm.

```
#if res['retcode'] > 0:                                                        
#    ret['result'] = False                                                     
#else:                                                                         
ret['changes'] = {'refresh': True}                                             

#if res['stdout'] and res['stderr']:                                           
#    ret['comment'] = "{0}\n{1}".format(res['stdout'], res['stderr'])          
#elif res['stdout']:                                                           
#    ret['comment'] = res['stdout']                                            
#elif res['stderr']:                                                           
#    ret['comment'] = res['stderr']                                            

return ret
```

I will update the thread after some more digging to either support or refute my theory.

**Comment by jbfriedrich** [comment]
I was able to confirm my suspicions. The commit from my last post is the culprit. The the function 'make_repo' in rpmbuild.py was extended to return '__salt__['cmd.run_all']' which means the function 'repo' in pkgbuild.py can check for the return code. The debbuild.py module **did not** get the same extension.
I would guess it is easily fixable with a different return handling based on os_family. I will re-open the issue that I filed with the salt project and create a PR request with a fix and close this issue once I have opened the other one. @dmurphy18, do you think that is the right approach?

**Comment by dmurphy18** [comment]
@jbfriedrich That sounds good, thanks for looking into this.
The same change needs to be made in both rpmbuild.py and debbuild.py to satisfy changes made in pkgbuild.py.

**Comment by dmurphy18** [comment]
Fix submitted https://github.com/saltstack/salt/pull/38035

**Comment by jbfriedrich** [comment]
Thank you @dmurphy18. I wasn't sure which way to go to fix this issue, as I had seen two possibilities. And then work got the better of me. Thanks for the fix!
