### ISSUE TITLE
Redhat 6 dependency incompatibilities between zeromq and zeromq3 

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#146]
https://github.com/saltstack/salt/issues/29132#issuecomment-247694357

Duplicated the issue with first installing salt-minion and the resulting installation of zeromq-4.0.5-4.el6.x86_64 and openpgm-5.2.12202.el6.

If you then try to install zeromq3 which wants openpgm-5.1.118-3.el6.x86_64 , you then get the error
root@tc6min:~# yum install zeromq3
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile

base: repos.lax.quadranet.com
epel: mirror.chpc.utah.edu
extras: centos.mirrors.hoobly.com
updates: mirror.chpc.utah.edu Resolving Dependencies --> Running transaction check ---> Package zeromq3.x86_64 0:3.2.5-1.el6 will be installed --> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.5-1.el6.x86_64 --> Finished Dependency Resolution Error: Package: zeromq3-3.2.5-1.el6.x86_64 (epel) Requires: libpgm-5.1.so.0()(64bit) Available: openpgm-5.1.118-3.el6.x86_64 (epel) libpgm-5.1.so.0()(64bit) Installed: openpgm-5.2.122-2.el6.x86_64 (@salt-latest) Not found You could try using --skip-broken to work around the problem You could try running: rpm -Va --nofiles --nodigest
Even with openpgm-5.2.122-2.el6.x86_64 already installed

Problem is use of zeromq v4.0.5  and zeromq3 v3.2.5 on the same machine, with their dependencies clashing, noting in Redhat 7, zeromq3 has been update to have a dependency on libpgm-5.2 rather than the libpgm-5.1 in Redhat 6.

Typically SaltStack has preferred using later versions of zeromq, due to various fixes and performance enhancements.  Investigating further as to best solution to resolve this issue.

**Comment by dmurphy18** [comment]
@fdamstra @f8al Digging further the issue of zeromq3 wanting openpgm-5.1 is curious since  in zeromq3 v3.2.3-2 it was rebuilt for openpgm-5.2, I am digging further.

**Comment by dmurphy18** [comment]
From investigating this, it appears the conflicit arises when openpgm from salt has been installed, but a regular install of salt-master or salt-minion doesn't install openpgm but does install zeromq, and 'yum -q deplist zeromq' is not listing openpgm. We should be able to build openpgm 5.1.118 for use with Redhat 6 on repo.saltstack.com and add note in next point release to remove openpgm 5.2.122 if installed, since it probably came from Salt's repo.

**Comment by dmurphy18** [comment]
@fdamstra @f8al Fix https://github.com/saltstack/salt-pack/pull/148 in PR.

**Comment by fdamstra** [comment]
I might not be following 100%, but it sounds to me like this is back to the original problem (#29132): The saltstack repo should not be supplying packages that are available in the base OS or EPEL repositories. As @racooper wrote there: "If the newer version is absolutely necessary, package it for parallel install with a different package name and leave the base packages alone."

**Comment by dmurphy18** [comment]
@fdamstra yes it now back to @racooper original problem

**Comment by carlwgeorge** [comment]
This is still a problem, why is this issue closed?

```
[root@EL6 ~]# yum --disablerepo=salt-latest --assumeyes --debuglevel=1 install python-zmq

============================================================================================================
 Package                    Arch                   Version                       Repository            Size
============================================================================================================
Installing:
 python-zmq                 x86_64                 14.3.1-1.el6                  epel                 467 k
Installing for dependencies:
 openpgm                    x86_64                 5.1.118-3.el6                 epel                 165 k
 zeromq3                    x86_64                 3.2.5-1.el6                   epel                 338 k

Transaction Summary
============================================================================================================
Install       3 Package(s)

Total download size: 970 k
Installed size: 2.8 M

Installed:
  python-zmq.x86_64 0:14.3.1-1.el6                                                                          

Dependency Installed:
  openpgm.x86_64 0:5.1.118-3.el6                        zeromq3.x86_64 0:3.2.5-1.el6                       

[root@EL6 ~]# yum --assumeyes --debuglevel=1 update
Error: Package: zeromq3-3.2.5-1.el6.x86_64 (@epel)
           Requires: libpgm-5.1.so.0()(64bit)
           Removing: openpgm-5.1.118-3.el6.x86_64 (@epel)
               libpgm-5.1.so.0()(64bit)
           Updated By: openpgm-5.2.122-2.el6.x86_64 (salt-latest)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

For what it's worth, you can work around the issue with yum shell.

```
[root@EL6 ~]# yum --assumeyes --debuglevel=1 shell
> erase zeromq3
> install zeromq
> update
> run

==============================================================================================================
 Package                  Arch                 Version                        Repository                 Size
==============================================================================================================
Installing:
 zeromq                   x86_64               4.0.5-4.el6                    salt-latest               568 k
Updating:
 openpgm                  x86_64               5.2.122-2.el6                  salt-latest               166 k
 python-zmq               x86_64               14.5.0-2.el6                   salt-latest               479 k
Removing:
 zeromq3                  x86_64               3.2.5-1.el6                    @epel                     1.3 M

Transaction Summary
==============================================================================================================
Install       1 Package(s)
Upgrade       2 Package(s)
Remove        1 Package(s)

Total download size: 1.2 M

Removed:
  zeromq3.x86_64 0:3.2.5-1.el6                                                                                

Installed:
  zeromq.x86_64 0:4.0.5-4.el6                                                                                 

Updated:
  openpgm.x86_64 0:5.2.122-2.el6                       python-zmq.x86_64 0:14.5.0-2.el6                      

> quit
```

Or in a one-liner: `printf 'erase zeromq3\ninstall zeromq\nupdate\nrun' | yum -y shell`

**Comment by carlwgeorge** [comment]
@dmurphy18 The `--disablerepo` flag only lasts for the duration of that one command, and is used to force the installation of EPEL's python-zmq initially in order to reproduce the issue.  You can accomplish the same demonstration on a brand new server just by having python-zmq installed before adding the salt repo.

```
[root@EL6 ~]# yum --assumeyes --quiet install python-zmq
[root@EL6 ~]# yum --assumeyes --quiet install https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el6.noarch.rpm
[root@EL6 ~]# rpm --import /etc/pki/rpm-gpg/saltstack-signing-key
[root@EL6 ~]# yum --assumeyes --quiet update
Error: Package: zeromq3-3.2.5-1.el6.x86_64 (@epel)
           Requires: libpgm-5.1.so.0()(64bit)
           Removing: openpgm-5.1.118-3.el6.x86_64 (@epel)
               libpgm-5.1.so.0()(64bit)
           Updated By: openpgm-5.2.122-2.el6.x86_64 (salt-latest)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

That is the crux of the issue: **adding the saltstack repository can break updates!**  This is why so many people are concerned about it.

This really doesn't have anything to do with openpgm, that is just showing up because I used `update` in my example instead of `update python-zmq`.  The work around works perfectly without updating openpgm if you explicitly just update python-zmq.

```
[root@EL6 ~]# rpm -q zeromq{,3} python-zmq
package zeromq is not installed
zeromq3-3.2.5-1.el6.x86_64
python-zmq-14.3.1-1.el6.x86_64
[root@EL6 ~]# yum --assumeyes --quiet shell
> erase zeromq3
> install zeromq
> update python-zmq
> run
> quit
[root@EL6 ~]# rpm -q zeromq{,3} python-zmq
zeromq-4.0.5-4.el6.x86_64
package zeromq3 is not installed
python-zmq-14.5.0-2.el6.x86_64
```

**Comment by dmurphy18** [comment]
Removing this unneeded dependency, see https://github.com/saltstack/salt-pack/issues/194
