### ISSUE TITLE
Size mismatch errors when using apt-cacher

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-pack#147]
I am submitting this issue because after speaking with @thatch45, we determined this was more of a salt-pack issue rather than a salt-bootstrap issue. The original is here: https://github.com/saltstack/salt-bootstrap/issues/961

Ping @KundK 
### Description of Issue/Question

Hi,

I'm using Ubuntu apt-cacher to decrease network traffic and prevent all servers having internet access.
But that cause a Size mismatch error on updating different versions of salt packages.

apt-cacher isn't storing source information of the packages. And because the salt packages for all versions (12.04, 14.04 and 16.04) have the same name (e.g salt-common_2016.3.3+ds-1_all.deb) it tries to provide the last one for a request. But they have different size (and content) which cause error for Apt.

I think the package name should contain either the version or codename of the target Ubuntu.
### Setup

Different versions of Ubuntu LTS servers are connected to the internet through a common Apt-cacher server.
### Steps to Reproduce Issue

First install/update salt on a Ubuntu 12.04 and then installing on a different Ubuntu version it'll fail with Size mismatch error.
### Versions and Systems

latest, 2016.3.3

**Comment by dmurphy18** [comment]
@KundK The problem you are experiencing is probably due to sources not working. Including the name of the OS in the package is not correct, and does not occur with the Debian Team's versions of Salt either, for example: https://packages.debian.org/stretch/salt-cloud

The naming of Salt packages is essentially that used by the Debian team, when SaltStack started to build Debian/Ubuntu packages, the same conventions were maintained.

**Comment by dmurphy18** [comment]
@KundK see https://github.com/saltstack/salt/issues/29608 already tracking this issue

**Comment by KundK** [comment]
Not a really good news when I can't automate the automation tool. 
But thanks for the response. Do you have an ETA for the fix?

**Comment by dmurphy18** [comment]
@KundK Sorry but I don't have an ETA, it is on my list but keeps getting pushed down with other more immediate issues, but I do want to resolve it soon.

**Comment by dmurphy18** [comment]
@KundK please see https://github.com/saltstack/salt/issues/29608.

Problems may be related to needing to import Salt's public key into your keyring

**Comment by dmurphy18** [comment]
@KundK Have you retried recently, note sources are downloadable. If you are unable to get to this, you could close this and reopen if it occurs when you retry.

**Comment by dmurphy18** [comment]
@KundK I tried with the newest release of Salt 2016.11.0 and apt-cacher on Ubuntu 12.04 and did not find any issue.  I would like to close this issue unless you have any objection or other information on the problems that you are seeing.

**Comment by KundK** [comment]
Hi, Yeah, go on. I don't have time to experiment now. But I'll disable my workaround. Let's see if the issue persist.
Thanks for the help!

**Comment by dmurphy18** [comment]
@KundK Thanks, you can always reopen this issue if it reoccurs
