### ISSUE TITLE
Including fish shell completion into platform packages

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt-pack#15]
Hi there,
is it possible to include the fish completion for SaltStack as in https://github.com/saltstack/salt/tree/develop/pkg/fish-completions into the SaltStack RPM files or provide them as extra RPM to get them easily?
Thanks and regards

*Copied from https://github.com/saltstack/salt/issues/30417.*

**Comment by lfudala** [comment]
It seems this is missing in the debs as well. Please increase scope to all packaged formats if possible as fish is widely available.

**Comment by jfindlay** [comment]
Ping @msteed, @cro, @jtand, @dmurphy18.

**Comment by dmurphy18** [comment]
Moved this to carbon since the latest fish completions in develop, hence carbon closer, also less disturbance to existing 2016.3 branch

**Comment by dmurphy18** [comment]
[X] Redhat 7
[X] Redhat 6
[X] Redhat 5
[ ]  Ubuntu 16.04
[ ]  Ubuntu 14.04
[ ]  Ubuntu 12.04
[ ] Debian 8
[ ] Debian 7

**Comment by dmurphy18** [comment]
Waiting for salt rc1 tarball

**Comment by jtand** [comment]
@dmurphy18 Will this be in Carbon?
