### ISSUE TITLE
Investigate building on Debian 9  - stretch

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#183]
Debian 9 is in Alpha 8, and already issues are araising, for example: recent issue with missing used label from libcrypto.so.1.1.

Hence would be good to start building internally for Debian 9 since it will soon enter Beta.
Noting that similar to Ubuntu 16, gpg > v2.1 is used requiring changes in how gpg-agent is used.

**Comment by dmurphy18** [comment]
Worked -around lintian issues, now experiencing issues running /usr/bin/gpg in pbuilder --create, ---build.
Also issue of apt-utils not available yet in Alpha.
Suspending till stretch (Debian 9) is further along. 

Note: seen on email threads that items need to be in before end-of-year to be included, hence expect beta sometime in January 2017.

**Comment by cachedout** [comment]
@dmurphy18 What is the current status of this? It was opened last December.

**Comment by dmurphy18** [comment]
@cachedout Moving this and future issues like it to icebox.  Debian 9 was too fragile in Alpha, so waiting for their Beta release and time to dig in again.  Maybe todo might be better for this, since Beta has to be close for Debian 9

**Comment by dmurphy18** [comment]
Debian 9 now has Release Candidate 3, https://www.debian.org/devel/debian-installer/News/2017/20170410

Need to restart this support effort, moving to backlog

**Comment by dmurphy18** [comment]
Debian has announced release date for 2017-06-17
https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html

**Comment by dmurphy18** [comment]
Running into issues with RC4, running pbuilder with simple package

The following packages have unmet dependencies:
apt-utils : Depends: apt but it is not going to be installed.

Similar with aptitiude.  Looking at the dependencies for these successfully installed packages, see Conflicts and Breaks in there, for example apt Breaks: apt-utils.  This is a little unstable, esp. since apt on Debian 8.8 does not have anything about apt-utils

**Comment by cachedout** [comment]
Wow. That's in a RC4?!

**Comment by dmurphy18** [comment]
@cachedout Release is scheduled for 2017-06-17, just a week away.

**Comment by dmurphy18** [comment]
Have Debian Rc4 building in nightly build for 2017.5, so will close this and create a new issue if anything arises once Debian 9 is released.
