### ISSUE TITLE
file conflict:  python27-futures from salt-amzn-latest 

### ISSUE THREAD

**Issue by paulsorensenmagnet** [saltstack/salt-pack#193]
Updating:
 python27-futures                           noarch                           3.0.3-2.amzn1                                 salt-amzn-latest                            29 k

Transaction check error:
  file /usr/lib/python2.7/dist-packages/futures-3.0.3.egg-info from install of python27-futures-3.0.3-2.amzn1.noarch conflicts with file from package python27-futures-3.0.3-1.3.amzn1.noarch

**Comment by dmurphy18** [comment]
@paulsorensenmagnet Thanks for letting us know, I shall look into the issue

**Comment by dmurphy18** [comment]
Removed from build scripts, waiting for next release

**Comment by dmurphy18** [comment]
@paulsorensenmagnet The latest relase Salt 2016.11.2 has removed python27-futures noarch 3.0.3-2.amzn1, this should resolve this issue.  Can you check and if satisfied, close this issue.

**Comment by dmurphy18** [comment]
@paulsorensenmagnet Closing this since fixed with the latest release of Salt 2016.11.2. If this is unsatisfactory, please feel free to re-open the issue providing additional details.
