### ISSUE TITLE
Debian Jessie packages depend on missing python-certifi

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt-pack#195]
Jessie stable doesn't have `python-certifi`, it is only present in `jessie-backports`. Salt should provide `python-certifi` package in own repos to make it installable on Jessie.

**Comment by dmurphy18** [comment]
@bobrik The SaltStack repository contains packages for Salt functionality and its dependencies for various platforms.  python-certifi is not a hard requirement or dependency for Salt functionality as present on repo.saltstack.com, hence Salt is not going to provide this package.

In the case of a Debian 8 installation without backports enabled, pip installing python-certifi would be a solution to your issue.

Hence closing this issue, however if this answer is unsatisfactory, please reopen it with further reasons or details as to why Salt should provide python-certifi.
