### ISSUE TITLE
Investigate package signing issues with Ubuntu 16.04

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#208]
Investigate gpg error reported when signing packages on recent Ubuntu 16.04.

Packages are signed correctly but some error is occurring after signing is completed, and the errors are throwing automation off

**Comment by dmurphy18** [comment]
Found reason and possible solution http://serverfault.com/questions/770130/reprepro-export-could-not-find-signing-key

This is basically due to use of gpg2 >= 2.1 and secring.ppg no longer used, with it only being read **ONCE**, to create the new private-keys-v1.d, add new key and it will be missed for use with gpg2

**Comment by dmurphy18** [comment]
Fixed the issue in auto_setup code for nightly_builds, but waiting to submit changes once nightly_builds functional

**Comment by cachedout** [comment]
@dmurphy18 I'm confused about where this is. It sounds like you want to do additional work and yet this is marked as `Done`? If there is additional work, please track it in another issue and close this one.
