### ISSUE TITLE
Overlapping file-defs in (EL7) RPMs

### ISSUE THREAD

**Issue by ferricoxide** [saltstack/salt-pack#210]
Both the `salt` and `salt-minion` RPMs claim ownership of the minion-log:
~~~
$ rpm -qf /var/log/salt/minion
salt-2016.11.2-1.el7.noarch
salt-minion-2016.11.2-1.el7.noarch
~~~
This should probably be changed so that only `salt-minion` claims ownership.

**Comment by dmurphy18** [comment]
Fix will be available in the next minor release, update spec file

**Comment by cachedout** [comment]
Set to `Done`. Closing.
