### ISSUE TITLE
SaltStack 2016.11.3 release causes key download 404 error

### ISSUE THREAD

**Issue by RonWilliams** [saltstack/salt-pack#220]
During SaltStack install with a new bootstrap, the following error occurs:

 *  INFO: Running install_red_hat_enterprise_linux_stable_deps()
warning: /var/tmp/rpm-tmp.e5lS4E: Header V3 RSA/SHA256 Signature, key ID 352c64e                 5: NOKEY
Retrieving https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rp                 m
Preparing...                          ########################################
Updating / installing...
epel-release-7-9                      ########################################
error: /tmp/salt-gpg-6CexgfoN.pub: key 1 not an armored public key.
 * ERROR: Failed to run install_red_hat_enterprise_linux_stable_deps()!!!

[roottmp]# cat /tmp/salt-gpg-6CexgfoN.pub
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /yum/redhat/7/x86_64/latest/base/RPM-GPG-KEY-CentOS-7 was not found on this server.</p>
</body></html>

The key is unavailable at http://repo.saltstack.com/yum/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub. The bootstrap previously worked on RHEL7 earlier today (02/28/17 10:54:52 MST), but does not work at this time.

**Comment by dmurphy18** [comment]
@RonWilliams  Missing the base sub--directory for Redhat 7 with Salt 2016.11.3, shall rebuilt repository with base sub-directory, and expect to have this issue fixed promptly

**Comment by RonWilliams** [comment]
@dmurphy18 Thank you sir!

**Comment by dmurphy18** [comment]
@RonWilliams the fix has gone to QA and should be available in the immediate future, once it is tested.

**Comment by dmurphy18** [comment]
@RonWilliams the repo.saltstack.com has been updated, see http://repo.saltstack.com/yum/redhat/latest/x86_64/archive/2016.11.3/base/RPM-GPG-KEY-CentOS-7

I am closing this issue as resolved, but if you find this unsatisfactory, please reopen it.
Thanks for bringing this to SaltStack's attention.

**Comment by RonWilliams** [comment]
@dmurphy18 Thank you very much for the quick fix. I can now confirm that the key download issue is now resolved. Salt can now be installed without error using the bootstrap.
