### ISSUE TITLE
Update salt.spec file for Redhat builds to include salt-syndic and salt-api usage with boot

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#221]
On Redhat 6, salt-syndic's  '%postun syndic' is commented out, this should be uncommented.

Also need to add support for salt-api and salt-syndic, similar to salt-minion and salt-master for all pre and post conditions.

**Comment by dmurphy18** [comment]
During development it was noticed that on Redhat 6 & 5, installation auto-enables with chkconfig. This is against Redhat's preferred practice and will be removed, Redhat 6 & 5 should operate similar to Redhat 7.
Installation installs but should not auto-enable.  Note that this is not the practice for Debian/Ubuntu where the preferred policy is to auto-enable and start on install.

**Comment by dmurphy18** [comment]
Updated time since noticed that a service salt-X restart is leaving old salt-X processes behind

**Comment by dmurphy18** [comment]
see https://github.com/saltstack/salt/issues/40068 to track grandchildren left behind.

**Comment by tsaridas** [comment]
@dmurphy18 I think the service left back is a known bug which I reported here 

https://github.com/saltstack/salt/issues/40011

I don't think the startup script has anything to do with the minion not being shutdown properly although we might as well want to make sure that we don't depend on netstat  to show us what is running but ps or something similar.

Concerning the auto enable on startup, I would keep it and add it to rh7 too but its your choice. My opinion is that users are used to have salt-minion auto enabled hence there should be consistency between OSs.

**Comment by dmurphy18** [comment]
@tsaridas Thanks for the information on saltstack/salt#40011

The auto enable on startup is against Redhat's preferred practices, but you have a point about leaving it as is for Redhat 6, for consistency with previous releases.

Given use of systemd on Redhat 7, I would prefer to do it right as it currently is with systemd.

**Comment by dmurphy18** [comment]
Moving forward with the minor releases, salt-minion and salt-master will remain auto enabling on startup when they are installed on Redhat 6 & 5 since this functionality has been present since 8 Jan 2012.
Current functionality of Redhat 7 where they are not auto enabled on install shall be preserved.

In the next major release of Salt for Redhat 6 & 5, the auto enabling of salt-minion and salt-master shall be removed.

**Comment by cachedout** [comment]
@dmurphy18 It looks like you have marked this as `Done`. Can it be closed?
