### ISSUE TITLE
bsdmainutils_9.0.6_amd64.deb should not be in saltstack's debian 7/8 repo.

### ISSUE THREAD

**Issue by osynge** [saltstack/salt-pack#222]
While raising the bug "packages updated without version upgrades" it was kindly pointed out by "Carsten Brandt" on IRC that the package bsdmainutils_9.0.6_amd64.deb is already in jessie:

As stated here:

    https://packages.debian.org/jessie/bsdmainutils

**Comment by dmurphy18** [comment]
It shall be removed with the next point release for Debian 8.

However the current version with Debian 7 is 9.0.3
root@dgm-chk-d7:~# apt-cache policy bsdmainutils
bsdmainutils:
  Installed: 9.0.3
  Candidate: 9.0.3
  Version table:
 *** 9.0.3 0
        500 http://ftp.us.debian.org/debian/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
root@dgm-chk-d7:~#

**Comment by dmurphy18** [comment]
Done in 2016.3.6

**Comment by dmurphy18** [comment]
Waiting for next point release 2016.11.4, as a reminder before closing
