### ISSUE TITLE
Build Salt 2016.3.6 packages 

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#229]
Note: last release to support Redhat 5 and Ubuntu 12.04

[x]  Redhat 7
[x]  Redhat 6
[x]  Redhat 5
[x]  Debian 8
[x]  Debian 7
[x] Raspbian 8
[x] Ubuntu 16.04
[x] Ubuntu 14.04
[x] Ubuntu 12.04

There is no Fedora release since 2016.11 branch is latest for Fedora

**Comment by dmurphy18** [comment]
Remember to update spec file and init scripts for changes applied to 2016.11 branch
see https://github.com/saltstack/salt-pack/issues/221 and https://github.com/saltstack/salt-pack/issues/190

**Comment by dmurphy18** [comment]
Need to update version of Cherry Py shipped with Redhat 6, see https://github.com/saltstack/zh/issues/1207#event-1014939714 and https://github.com/saltstack/salt/issues/34234

**Comment by cachedout** [comment]
@dmurphy18 If you don't already have an issue to track the update of CherryPy for RHEL 6 could you please open one and then close this? Thanks.
