### ISSUE TITLE
Build python-cherrypy rpm for Redhat 6 and 7

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#231]
Need to build a version of python-cherrypy with at least version 10.1.1 for Redhat 6 see following:
https://github.com/saltstack/salt-pack/issues/229
saltstack/zh#1207 (comment) 
saltstack/salt#34234

**Comment by dmurphy18** [comment]
Changed to approved since this will not be a quick thing and need to build-able on Redhat 6 with  Python 2.6 given their page states support for Python 2.7 to 3.5, see url: http://docs.cherrypy.org/en/latest/install.html#supported-python-version

However, given history on change v10.2.1, they still run on Python 2.6, maybe just not official support

**Comment by dmurphy18** [comment]
SSL issue with cherrypy https://github.com/cherrypy/cherrypy/issues/1298
jumping from current 3.2.2. to 10.2.1 may be too large a jump, also from v6.0.0 CherryPy moved to using setuptools, of which Redhat 6 has too early a version to build.  CherryPy v5.6.0 was the last to use distutils as a dependency to build and may be a better fit for building on Redhat 6.  
SaltStack is testing with that version to see if it will be satisfactory.  The salt-api race condition was fixed in the v3.x timeframe, but those versions have ssl issues, and best to pick a version which has no race condition or ssl problems, but closer to the shipping versions for Redhat.

**Comment by dmurphy18** [comment]
Versions of CherryPy to consider

3.5.0-1  highest version available since Fedora 22 from Redhat space
3.8.2  last version which still had support for Python 2.5
5.8.2 last version where distutils was used to built, after this needed setup tools, complicating spec file required.

**Comment by dmurphy18** [comment]
Built version 5.6.0 successfully for Redhat 7 & 6, shall use this version.

**Comment by dmurphy18** [comment]
Decided to leave Amazon alone due to unlikely need for AMI support for later version of cherrypy

**Comment by rickh563** [comment]
ZD-1245
