### ISSUE TITLE
Add package support for pycryptodomex for Salt 2016.11 branch

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#234]
[x] Redhat 7
[x] Redhat 6
[] Debian 8
[] Debian 7
[] Raspbian (Debian 8)
[] Ubuntu 16.04
[] Ubuntu 14.04
[] Amazon

**Comment by dmurphy18** [comment]
Building dependencies libtommath and libtomcrypt too

**Comment by dmurphy18** [comment]
Having pycrptodomex and its dependencies building for Redhat 7 & 6, and passing it's tests successfully.
Still to check that it is orthogonal to use of pycrypto.

**Comment by dmurphy18** [comment]
Working Debian  / Ubuntu

**Comment by dmurphy18** [comment]
Note Redhat 7 & 6 implementation has been added to Salt 2016.11.4

**Comment by cachedout** [comment]
Which issue are we tracking which is blocking this one?

**Comment by dmurphy18** [comment]
The blocking is due to time, got Redhat 6 & 7 done, was in-progress for Debian / Ubuntu, but had to put on hold for point release.  Redhat 6 & 7 got added Salt 2016.11.4 due to commercial pressures.

**Comment by dmurphy18** [comment]
Only going to support pycryptodomex on Redhat 6 & 7 which now exists with Salt 2016.11.4 release
Hence closing this issue since already delivered for Redhat 6 & 7
