### ISSUE TITLE
Redhat 6 winexe fails to install

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#236]
Versions of winexe from 2016.3.3 and 2016.11.3 now fail to install on latest Redhat 6, suspect that the dependencies have changed.

root@tc6min:~# yum install winexe
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.pdx.edu
 * epel: linux.mirrors.es.net
 * extras: mirror.chpc.utah.edu
 * updates: mirrors.syringanetworks.net
Resolving Dependencies
--> Running transaction check
---> Package winexe.x86_64 0:1.1-1b787d2.el6 will be installed
--> Processing Dependency: liberrors.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1b787d2.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1b787d2.el6.x86_64
--> Processing Dependency: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1b787d2.el6.x86_64
--> Processing Dependency: liberrors.so()(64bit) for package: winexe-1.1-1b787d2.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so()(64bit) for package: winexe-1.1-1b787d2.el6.x86_64
--> Processing Dependency: libcli-ldap.so()(64bit) for package: winexe-1.1-1b787d2.el6.x86_64
--> Finished Dependency Resolution
Error: Package: winexe-1.1-1b787d2.el6.x86_64 (salt-latest)
           Requires: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit)
Error: Package: winexe-1.1-1b787d2.el6.x86_64 (salt-latest)
           Requires: libcli-ldap.so()(64bit)
Error: Package: winexe-1.1-1b787d2.el6.x86_64 (salt-latest)
           Requires: liberrors.so(SAMBA_4.0.0RC4)(64bit)
Error: Package: winexe-1.1-1b787d2.el6.x86_64 (salt-latest)
           Requires: libdcerpc-samba.so()(64bit)
Error: Package: winexe-1.1-1b787d2.el6.x86_64 (salt-latest)
           Requires: liberrors.so()(64bit)
Error: Package: winexe-1.1-1b787d2.el6.x86_64 (salt-latest)
           Requires: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by dmurphy18** [comment]
Probably due to latest samba4 is now version 4.2.10-9 rather than a release candidate.  Should fix this with the 2016.11.4 release in packaging

**Comment by dmurphy18** [comment]
This looks to be due to some names having recently changed, causing the following failure on Redhat 6, Redhat 7 build fine.
9406 /builddir/build/BUILD/samba/wscript:107: error: the configuration failed (see '/builddir/build/BUILD/samba/bin/config.log')
9407 Checking for library smb_static                                     : not found
9408 Build of static winexe                                              : disabled
9409 Cannot continue! Please either install Samba shared libraries and re-run waf, or download the Samba source code and re-run waf with the "--samba-dir" option.
9410 (complete log in /builddir/build/BUILD/winexe-1.1/source/build/config.log)
9411 RPM build errors:

Going to build Salt 2016.11.4 point release without winexe and fix later

**Comment by cachedout** [comment]
Which issue is this blocked on?

**Comment by dmurphy18** [comment]
Not building anymore on Redhat 6, and a quick google gave some renaming and items going dynamic rather than static. Looked like more than a couple of hours, so took it out of the point release for Salt 2016.11.4, since it is there as a convenience for users, not part of Salt.

Did not want to delay release, will dig deeper once all of Salt 2016.11.4 is released since still finish Fedora and AIX / Solaris to do.  Will be able to dig deeper beginning next week

**Comment by dmurphy18** [comment]
Looks like and issue with samba > 4.1 see url https://sourceforge.net/p/winexe/bugs/77/

**Comment by dmurphy18** [comment]
Updated the Redhat 6 support for winexe to utilize samba libraries, differs from that used on Redhat 7 and Amazon. Redhat 7 utilizes  samba 4.4.4 which appears not to have the issues of the samba 4.2.x that Redhat 6 has.

Note: winexe appears to have gone fallow and with Windows 10 updates for Linux support may not be required moving forward into the future

**Comment by dmurphy18** [comment]
Installs on Redhat 6 system, test tomorrow morning once Shane has a Windows system to test with
