### ISSUE TITLE
python-simplejson not in redhat/7* saltstack repo

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt-pack#31]
*Moved from https://github.com/saltstack/salt/issues/31036.* @lorengordon

In Enterprise Linux 6 distros, `python-simplejson` is in the repos included with the distribution. In Enterprise Linux 7, it seems it is not (I checked rhel7 and centos7). `python-simplejson` is a dependency of `python-raet`, so to use the raet transport in EL7, there is a dependency on the EPEL repo.

My understanding at the moment is that the saltstack repo is supposed to include all packages and dependencies such that there should be no dependency on EPEL. If that understanding is correct, please add `python-simplejson` to the saltstack repo for EL7.

**Comment by lorengordon** [comment]
Thanks @jfindlay. I _almost_ opened the issues here, but wasn't positive you all wanted to track issues in different places across the different projects. :D

**Comment by jfindlay** [comment]
@lorengordon, it's not a big deal.  I am only grateful you reported the issue. :)

**Comment by dmurphy18** [comment]
Fixed with PPR #42 , should be available with the next point release
