### ISSUE TITLE
libcloud_dns doesn't work on CentOS 7 due to too old libcloud

### ISSUE THREAD

**Issue by kyrias** [saltstack/salt-pack#311]
The python-libcloud package on CentOS 7 is version 0.20.1, but the libcloud_dns execution module requires 0.21.0 minimum.

**Comment by kyrias** [comment]
(And libcloud_dns in salt git requires 2.0.0, so would want to be planning for that jump as well.)

**Comment by dmurphy18** [comment]
see Update libcloud to newer versions for Redhat, Debian and Ubuntu #314
This update will  be available with the next major version release (Nitrogen)

**Comment by dmurphy18** [comment]
@kyrias Have you tested with the latest point releases as this was fixed some time ago.

**Comment by dmurphy18** [comment]
@kyrias The version of libcloud was updated in the summer of 2017 to version 2.0.0, hence I am closing this issue, but please reopen it if your issue has not been resolved by the updated version of libcloud.
