### ISSUE TITLE
Requesting a static URL for latest salt release repo RPM

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt-pack#317]
It would really be convenient to have a static URL to the latest salt repo RPM. It used to be:

* https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el6.noarch.rpm

and now it is:

* https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el6.noarch.rpm

Unfortunately, now anything that was referencing the prior URL is now breaking and needs to be updated to use the new URL. This seems contrary to the point of even having a "latest" RPM for the release repo.

**Comment by bdeluca** [comment]
+1 In the same predicament.

**Comment by lorengordon** [comment]
Noticed that this affects the "pin to major version" repo RPMs, as well as "latest". And of course, both el7 and el6.

**Comment by cmclaughlin** [comment]
I haven't tried it, but perhaps this is what you're looking for?

https://repo.saltstack.com/yum/redhat/latest/x86_64/saltstack-rhel7.repo

**Comment by mbochenk** [comment]
@cmclaughlin some people either cannot use repo file or for other reasons setup via package. Again, the file may change, there may be other legitimate constraints.
This may be not a static link but a redirect, for example - for example, ```salt-latest``` redirects to ```salt-latest-2.rpm```, etc.

**Comment by bdeluca** [comment]
There should be one correct way, so we know what it is, are we meant to be using a repo file or the rpm? If we are meant to be using the repo file the documentation should reflect that.

**Comment by lorengordon** [comment]
@cmclaughlin I don't think so. Pretty sure that `redhat/latest` path is more or less deprecated. Far as I've seen, only amazon linux resolves `$releasever` to `latest`, and now salt has a [different path for amazon](http://repo.saltstack.com/yum/amazon/).

And sure, we could write out the repo file, or save the one provided at the correct [$releasever path](https://repo.saltstack.com/yum/redhat/6/x86_64/saltstack-rhel6.repo). I don't mind there being more than one way to get it done; there always is more than one way. But it would be nice if the documented method for pinning to a latest or major version stayed consistent over time. The moving target is the problem.

**Comment by dmurphy18** [comment]
The repo file was a temporary solution until the install repo rpm's could be updated, but that was quite some time ago.  The repo file's will be removed in another major release branch and a symbolic link for the various major branches shall be created for latest, 2017.7, 2016.11, 2016.3 etc.

**Comment by lorengordon** [comment]
@dmurphy18 Are you saying that the symbolic link will be to the current release rpm that installs the repo definition?

**Comment by dmurphy18** [comment]
@lorengordon Proposing a symbolic link that will provide an unchanging link to install the current install release rpm, one could also use the specific version too, for example

salt-repo-latest.el7.noarch.rpm -> salt-repo-latest-2.el7.noarch.rpm
salt-repo-2017.7.el6.noarch.rpm -> salt-repo-2017.7-1.el6.noarch.rpm

Details still to be worked out and tested with considered input.  Please let me know you thoughts on the matter.

**Comment by lorengordon** [comment]
@dmurphy18 That sounds great, thanks!

If you're surveying for how others do this, maybe look at epel:

- https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
- https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

From [here](https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F). I also like the way they link to the signing keys for verification.

**Comment by lorengordon** [comment]
With epel, in particular, note the name of the rpm file compared to the name of the extracted cpio...

**Comment by dmurphy18** [comment]
Updated staging with permanent fixed symbolic links to current branch install repo rpms

# Redhat
salt-repo-2015.8.el6.noarch.rpm -> salt-repo-2015.8-4.el6.noarch.rpm
salt-repo-2016.11.el6.noarch.rpm -> salt-repo-2016.11-2.el6.noarch.rpm
salt-repo-2016.3.el6.noarch.rpm -> salt-repo-2016.3-2.el6.noarch.rpm
salt-repo-2017.7.el6.noarch.rpm -> salt-repo-2017.7-1.el6.noarch.rpm
salt-repo-2018.3.el6.noarch.rpm -> salt-repo-2018.3-1.el6.noarch.rpm
salt-repo-latest.el6.noarch.rpm -> salt-repo-latest-2.el6.noarch.rpm

salt-repo-2015.8.el7.noarch.rpm -> salt-repo-2015.8-4.el7.noarch.rpm
salt-repo-2016.11.el7.noarch.rpm -> salt-repo-2016.11-2.el7.noarch.rpm
salt-repo-2016.3.el7.noarch.rpm -> salt-repo-2016.3-2.el7.noarch.rpm
salt-repo-2017.7.el7.noarch.rpm -> salt-repo-2017.7-1.el7.noarch.rpm
salt-repo-2018.3.el7.noarch.rpm -> salt-repo-2018.3-1.el7.noarch.rpm
salt-repo-latest.el7.noarch.rpm -> salt-repo-latest-2.el7.noarch.rpm

# Amazon
salt-amzn-repo-2016.11.amzn1.noarch.rpm -> salt-amzn-repo-2016.11-1.amzn1.noarch.rpm
salt-amzn-repo-2017.7.amzn1.noarch.rpm -> salt-amzn-repo-2017.7-1.amzn1.noarch.rpm
salt-amzn-repo-2018.3.amzn1.noarch.rpm -> salt-amzn-repo-2018.3-1.amzn1.noarch.rpm
salt-amzn-repo-latest.amzn1.noarch.rpm -> salt-amzn-repo-latest-2.amzn1.noarch.rpm

salt-amzn2-repo-2017.7.amzn2.noarch.rpm -> salt-amzn2-repo-2017.7-2.amzn2.noarch.rpm
salt-amzn2-repo-2018.3.amzn2.noarch.rpm -> salt-amzn2-repo-2018.3-2.amzn2.noarch.rpm
salt-amzn2-repo-latest.amzn2.noarch.rpm -> salt-amzn2-repo-latest-2.amzn2.noarch.rpm

**Comment by dmurphy18** [comment]
Updates for Python 3 on staging

# Python 3
# Redhat
salt-py3-repo-2018.3.el7.noarch.rpm -> salt-py3-repo-2018.3-1.el7.noarch.rpm
salt-py3-repo-latest.el7.noarch.rpm -> salt-py3-repo-latest-2.el7.noarch.rpm


These links should be available with the next point release

**Comment by dmurphy18** [comment]
@lorengordon sorry for taking so long with this, but this should become available with the next release.  However I am sure you have probably worked around it given the time frame.

**Comment by lorengordon** [comment]
All good @dmurphy18, thanks! 😁
