### ISSUE TITLE
package key process and keyserver support

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt-pack#33]
1.  When we create a new major release we should consider whether to use a new encryption key to be used with that release based on the guaranteed support lifetime of that release and whether it terminates before the key expires.  This will not need to happen for every major release, but must happen for major releases whose lifetimes extend beyond the expiration of the current key.  In this way it should be easier for users to upgrade package keys with salt releases rather than have to retrofit existing deployments with a new package key.

2. We should get our repo key(s) supported by upstream key servers for users who want/need the additional validation from an external, trusted authority.

**Comment by jfindlay** [comment]
https://github.com/saltstack/salt/issues/27511#issuecomment-148517693

**Comment by dmurphy18** [comment]
current keys never expire:

pub  2048R/DE57BFBE  created: 2014-06-24  expires: never       usage: SC  
                     trust: unknown       validity: unknown
sub  2048R/17928113  created: 2014-06-24  expires: never       usage: E   
[ unknown] (1). SaltStack Packaging Team <packaging@saltstack.com>

**Comment by UtahDave** [comment]
What's the proper thing here?

**Comment by dmurphy18** [comment]
@UtahDave Do we go and get our keys signed by some trusted entity ?

or do we care ?

**Comment by dmurphy18** [comment]
Closing this, since our keys don't expire
