### ISSUE TITLE
file name incorrect

### ISSUE THREAD

**Issue by carlwgeorge** [saltstack/salt-pack#34]
The current salt-repo packages on [this page](http://repo.saltstack.com/#rhel) have an incorrect file name.  The filename `salt-repo-2015.8.el7.noarch.rpm` would indicate the following properties:

name: `salt-repo`
version: `2015.8`
release: `.el7`
architecture: `.noarch`

The actual release of the RPM is `2.el7`.

```
$ rpm --query --package --queryformat '%{release}\n' salt-repo-2015.8.el7.noarch.rpm 
2.el7
```

The same problem affects the el6 and el5 packages as well.  Please correct the filenames (and download links of course) to match the actual properties of the RPM.

**Comment by dmurphy18** [comment]
@carlwgeorge The spec file for the release field is similar to 2%{?dist} which includes the distribution as part of the release, hence the release is correctly stated as '2.el7' for release 2 for epel on Redhat 7.  This is similar to the example 'Release:	1%{?dist}' in https://fedoraproject.org/wiki/How_to_create_an_RPM_package#Spec_file_pieces_explained.  I believe the release value is stated correctly.

**Comment by carlwgeorge** [comment]
I fully understand how the dist macro works.  What is inconsistent is the filename of the RPM.

> The current salt-repo packages on this page have an incorrect file name. 

With a release of `2.el7`, the filename should be `salt-repo-2015.8-2.el7.noarch.rpm`, not `salt-repo-2015.8.el7.noarch.rpm`.

```diff
-salt-repo-2015.8.el7.noarch.rpm
+salt-repo-2015.8-2.el7.noarch.rpm
```

**Comment by dmurphy18** [comment]
@carlwgeorge I see what you mean now. I shall take a closer look

**Comment by dmurphy18** [comment]
Updated signed salt-repo-xxx.rpm ready for test
