### ISSUE TITLE
Create Raspbian Stretch armhf support

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#342]
Need to create stretch based support for Raspbian similar to jessie.
Backport nitrogen version to 2016.11 branch.

**Comment by dmurphy18** [comment]
Waiting for Raspbian to release their support for Debian 9 (stretch).
They have a version of stretch in their downloads but not ready for prime time yet

**Comment by dmurphy18** [comment]
Raspbian Stretch has arrived Aug 17 2017 https://www.raspberrypi.org/blog/raspbian-stretch
Need to move this up

**Comment by dmurphy18** [comment]
Created Raspbian 9 image and salt-minion (2016.11.2 - Debian's build) on Pii.
Also created build script for 2017.7.2 build

**Comment by dmurphy18** [comment]
Running into issues with pbuilder --create, the debootstrap is failing with various packages failing to download, that is, network connectivity, is having issues and appears to be random, different packages on different occasions.  Further dirmngr is MIA in that not getting installed by bootstrap.  Think Raspbian has missed something with the transition in Debian 9 to gnupg v2.1.18.

Note this is from running pbuilder --create on the command line, - Salt not involved.

**Comment by dmurphy18** [comment]
Debian 9.2 just got released with fixes, for example issues with dirmngr

**Comment by dmurphy18** [comment]
Raspbian Stretch as of Nov 16 is still on Debian 9.1 and as such does not yet contain the fixes from Debian 9.2

**Comment by forty8bits** [comment]
@dmurphy18 any update? Latest version of Raspbian Stretch was released on the 29th of November. :crossed_fingers:

**Comment by dmurphy18** [comment]
@forty8bits Just pulled down the update and notice it still reports Debian 9.1 (lsb_release -a).  However I shall try to rebuild latest salt for Raspbian 9 and see if the build issues have been resolved.

**Comment by sw25481** [comment]
I did a dist-upgrade today and I get

scott@raspberrypi ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

Repos contain 

salt-common all 2016.11.2+ds-1
salt-minion all 2016.11.2+ds-1

Looking forward to 2017.7.2

**Comment by dmurphy18** [comment]
@sw25481 Thanks for the info, I shall retry again now the Christmas break is over

**Comment by dmurphy18** [comment]
Updated to Debian 9.3 and seeing issues with gpg (2.1.18) not working well with dirmngr
Investigating

**Comment by dmurphy18** [comment]
Issue is gpg-agent not getting started successfully from setup. Also G04 importkeys is being run after the stretch.tgz is created (pbuilder --create) but keys needed for stretch.tgz, chicken and egg problem first time through,

**Comment by bbinet** [comment]
I'm also very interested in a raspbian stretch working salt-minion. Anything I can do to help here?

**Comment by dmurphy18** [comment]
@bbinet Takes for the offer of help.

The problem running into is that the gpg-agent is not getting started correctly (not at all gpg2 2.1.118) from setup.debian.debian9 with the updated 9.3 on the armhf (Pi II).  Also moving G04importkeys such that is run earlier with pbuilder so that on a clean system the Raspbian keys are installed would help.
Works if I start the gpg-agent by hand after running setup on the salt-minion (Pi II box)

The current code is essentially that already which is already present in 2017.7.2 on salt-pack which is open-sourced, hence any contribution gladly accepted.  Additionally if you see anything which can be improved or corrected, please adjust and submit a PR.

Lastly SaltStack is soon to be making new point releases hence I would like to incorporate any fixes before the new point releases.

Thanks

**Comment by dmurphy18** [comment]
Problem is occurring in Unicode handling for 

3301 Traceback (most recent call last):
3302   File "/usr/lib/python2.7/logging/__init__.py", line 872, in emit
3303     stream.write(ufs % msg)
3304   File "/usr/lib/python2.7/codecs.py", line 706, in write
3305     return self.writer.write(data)
3306   File "/usr/lib/python2.7/codecs.py", line 370, in write
3307     self.stream.write(data)
3308 IOError: [Errno 9] Bad file descriptor

Given all of the UTF-8 work ongoing in Oxygen release, going to start gpg-agent by hand and retry to resolve this once Oxygen and the UTF-8 work is released.

Blocking till recheck with Oxygen point release

**Comment by dmurphy18** [comment]
Built with manual starting of gpg-agent and even then passphrase was not automatic.
