### ISSUE TITLE
Oxygen Salt packages for Python 3.4 - Redhat 7

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#360]

**Comment by dmurphy18** [comment]
Current Python 3 support for Redhat 7 is completed with prefix python3-xxxxx.
However thinking need to change this to python34-xxxxx to better match Redhat packages and  better utilize Redhat tools, for example provide macros.

Waiting for decision on changing naming of packages, that is, 's' post-fixed and 'salt' before distribution, for example: python34-chardet**s**-a.b.c-2.**salt**.el7.rpm

**Comment by carlwgeorge** [comment]
FYI, python34 is an EPEL thing, not directly from Red Hat.

Also, the [transition is under way to switch to python36](https://lists.fedoraproject.org/archives/list/epel-announce@lists.fedoraproject.org/thread/VLTFSZEQHXBZHHDAKMT4KCQEKPSFV5OS/).

**Comment by dmurphy18** [comment]
@carlwgeorge Thanks for that information, already seen a few Python 3.6 packages in the wild. 

SaltStack will be relying on EPEL's Python 3 support for Redhat 7 since it doesn't make sense to re-invent the wheel when not necessary. Dependent on time of release of Oxygen, the support for Python 3.4 or Python 3.6 is just a rebuild of the packages, which is now mostly automated, hence will use whichever is prevalent at time of release from development to QA for testing and release.
