### ISSUE TITLE
salt-repo package is unsigned

### ISSUE THREAD

**Issue by carlwgeorge** [saltstack/salt-pack#37]
Packages from the SaltStack repository are signed, but the salt-repo package used to enable the repository is not.

```
$ rpm --checksig *.rpm
salt-2015.8.5-1.el7.noarch.rpm: rsa sha1 (md5) pgp md5 OK
salt-repo-2015.8.el7.noarch.rpm: sha1 md5 OK
```

Please sign the salt-repo packages with the same key as the other packages.

**Comment by carlwgeorge** [comment]
This is true for the RHEL 5, 6, and 7 versions of the package.

**Comment by dmurphy18** [comment]
Updated signed salt-repo-xxx.rpm ready for test
