### ISSUE TITLE
python-jinja2 is downgraded on jessie->stretch upgrade

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt-pack#376]
On Jessie salt repos provide packaged `python-jinja2=2.9.4-1`:

* http://repo.saltstack.com/apt/debian/9/amd64/archive/2017.7.0/

On Stretch there is no such package and Debian itself only provides `python-jinja=2.8`:

* http://repo.saltstack.com/apt/debian/8/amd64/archive/2017.7.0/

```
root@moby:/# apt-cache madison python-jinja2
python-jinja2 |      2.8-1 | https://deb.debian.org/debian stretch/main amd64 Packages
```

This downgrade broke `tojson` filter usage for us, it got added in jinja2 v2.9:

* https://github.com/pallets/jinja/commit/e71a130607fe5d21e2ee2544f4c6c90e8d5591b5

I think salt should continue providing more up to date `python-jinja2` package.

**Comment by dmurphy18** [comment]
@bobrik sorry for this inconvenience, with the next point release for Debian 9 (which should be soon), the same version of Jinja2 shall be made available that was used in Debian 8.

**Comment by bobrik** [comment]
@dmurphy18 thanks, I worked around this by installing `jinja2` from `pip` (we run master in docker container, so it acceptable-ish). Looking forward to the next release!
