### ISSUE TITLE
RHEL install directions should use yum, not rpm

### ISSUE THREAD

**Issue by carlwgeorge** [saltstack/salt-pack#39]
The [repository installation instructions](http://repo.saltstack.com/#rhel) instruct users to use rpm directly to install the salt-repo packages.

```
rpm -ivh https://repo.saltstack.com/yum/redhat/salt-repo-2015.8.el7.noarch.rpm 
```

This is wrong because it alters the rpm database outside of yum.  Here are better commands for RHEL 5, 6, and 7.

RHEL 7:
```
yum install https://repo.saltstack.com/yum/redhat/salt-repo-2015.8.el7.noarch.rpm
```
RHEL 6:
```
yum install https://repo.saltstack.com/yum/redhat/salt-repo-2015.8.el6.noarch.rpm
```
RHEL 5:
```
wget https://repo.saltstack.com/yum/redhat/salt-repo-2015.8.el5.noarch.rpm
yum localinstall salt-repo-2015.8.el5.noarch.rpm
rm -f salt-repo-2015.8.el5.noarch.rpm
```

I would submit a pull request to the docs directly, but I can't find them.

**Comment by dmurphy18** [comment]
@carlwgeorge I shall take a look into this and change accordingly.  Thanks for the information.

**Comment by dmurphy18** [comment]
@jacobhammons  Checked the commands and no issue, think that we should update the doc's accordingly

**Comment by carlwgeorge** [comment]
I just noticed a small issue.  On EL5, `yum localinstall` won't work with an unsigned package (see also #37).  The EL5 instructions should instead read:

```
wget https://repo.saltstack.com/yum/redhat/salt-repo-2015.8.el5.noarch.rpm
rpm -Uvh salt-repo-2015.8.el5.noarch.rpm
rm -f salt-repo-2015.8.el5.noarch.rpm
```

**Comment by dmurphy18** [comment]
@jacobhammons see above

**Comment by dmurphy18** [comment]
Now have updated signed and correctly name salt-repo-xxx.rpm for 2015.8 and 2015.5 branches ready for test with the new documentation.
salt-repo package is unsigned #37
file name incorrect #34

**Comment by dmurphy18** [comment]
also file name incorrect #34
