### ISSUE TITLE
Packages for Debian 9 arm64

### ISSUE THREAD

**Issue by petrhosek** [saltstack/salt-pack#459]
Would it be possible to build and provide packages for Debian 9 arm64 at https://repo.saltstack.com/? We're using Salt for managing Debian 9 arm64 with the packages installed from the Debian APT repository (https://packages.debian.org/stretch/salt-minion) but those are already outdated (the latest version is 2016.11.2) and we would like to update to the latest version.

**Comment by petrhosek** [comment]
We're using Cavium ThunderX based [Gigabyte servers](http://b2b.gigabyte.com/ARM-Server). Scaleway is also using these in their [ARMv8 cloud service](https://www.scaleway.com/armv8-cloud-servers/). It may be worth checking with them if they would be willing to provide an instance to Salt for testing and packaging.

**Comment by bobrik** [comment]
Debian provides packaged with arch set to `all`. I don't see any arch-specific things in salt package, so maybe it's worth doing the same here?

**Comment by dmurphy18** [comment]
@petrhosek @bobrik FYI there are Debian 9 (stretch) packages available with point release 2017.7.3, they are just not yet advertised on the Web landing page, it will be updated soon.

However if you follow the instructions for Raspbian Jessie and replace 8 with 9, jessie with stretch, it should install and function correctly.

**Comment by dmurphy18** [comment]
Blocked as reminder, Need QA to update Web landing page

**Comment by bobrik** [comment]
@dmurphy18, I only see `armhf` arch, but we ask for `arm64` here.

* https://repo.saltstack.com/apt/debian/9/
* https://wiki.debian.org/ArmHardFloatPort
* https://wiki.debian.org/Arm64Port

**Comment by dmurphy18** [comment]
@bobrik Sorry read title too quickly.  Currently only building for ARM with Raspberry Pi 2 as a base level.  Been waiting for Pi's to update to ARM 64, Pi 3 is capable but firmware limits it. SaltStack has plans for ARM64 for hardware, but I am unsure of any timelines.

**Comment by bobrik** [comment]
When I look here:

* https://repo.saltstack.com/apt/debian/9/amd64/archive/2017.7.2/

I see all packages with `all` arch. It seems that supporting `arm64` is a matter of building repo index for `arm64` here:

* https://repo.saltstack.com/apt/debian/9/amd64/archive/2017.7.2/dists/stretch/main/

No extra package builds are needed. In fact, we mirror salt repo and that took care of creating appropriate `dists` for us.

**Comment by alexandruavadanii** [comment]
Hi,
I did not see this ticket till now.
All Salt packages are indeed arch-indep (even most of its deps).
See [1] for a more detailed investigation. We have been using the amd64 repos on arm64 without any issue. We also used to build the dependencies from sources, which works just fine on arm64 too.

In case you didn't use this before, you can add an amd64 repo on an arm64 Debian system with something like this:
deb [arch=amd64] http://

apt-get will 'see' only the arch-indep packages from that repo, but in this case, it's more than enough.

[1] https://jira.opnfv.org/browse/ARMBAND-382

**Comment by nlamirault** [comment]
I confirm. I juste upgrade my repository list file and it works fine : 

```bash
$ uname -a
Linux jarvis-master 4.4.77-rockchip-ayufan-136 #1 SMP Thu Oct 12 09:14:48 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

$ dpkg -l|grep salt
ii  salt-cloud                               2018.3.2+ds-1                              all          public cloud VM management system
ii  salt-common                              2018.3.2+ds-1                              all          shared libraries that salt requires for all packages
ii  salt-master                              2018.3.2+ds-1                              all          remote manager to administer servers via salt

$ sudo cat /etc/apt/sources.list.d/repo_saltstack_com_apt_debian_9_amd64_2018_3.list 
deb [arch=amd64] http://repo.saltstack.com/apt/debian/9/amd64/2018.3 stretch main
```

**Comment by alexandruavadanii** [comment]
For the record, https://github.com/saltstack/salt-bootstrap/issues/1240 was fixed and the latest Salt bootstrap scripts got a new release with support for arm64 using amd64 repos as described above.

**Comment by dmurphy18** [comment]
@petrhosek Salt has a new feature request process, hence if this is still of interest to you, can you please close this issue an make a request here https://github.com/saltstack/salt-enhancement-proposals
