### ISSUE TITLE
Salt 2016.11: incompatible python-cherrypy package

### ISSUE THREAD

**Issue by vutny** [saltstack/salt-pack#478]
Hi @dmurphy18 

This issue is related to saltstack/salt#43581 .
It appears that `python-cherrypy-5.6.0-1.el7.noarch.rpm` from https://repo.saltstack.com/yum/redhat/7/x86_64/2016.11/ is cannot be used out-of-the-box with Salt API in release 2016.11.X.
However, here is updated version: https://repo.saltstack.com/yum/redhat/7/x86_64/latest (5.6.0-2).

For the sake of consistency and having smooth bootstrapping of Salt API from previous release, would you consider to build and upload patched `python-cherrypy` into `2016.11` archive? I believe this affects both RHEL 6 and 7.

Thank you.

**Comment by vutny** [comment]
Corrected issue topic. I meant Salt 2016.11 (Carbon).

**Comment by dmurphy18** [comment]
@vutny this is issue was probably introduced with a patched version for the 2017.7 branch to work-around an issue on that branch.  There will soon be point release updates for both 2016.11 and 2017.7 branches which should resolve the issue seen, that is both will be generated without the patch for 2017.7 branch.

If this information resolves the issue for you, can you consider closing this issue or alternatively wait and check if it is resolved once the point releases have been made.

**Comment by dmurphy18** [comment]
@vutny Given the recent releases, can you check if your concerns are fixed and if so close this issue. 
Thanks

**Comment by vutny** [comment]
Thank you @dmurphy18 . I will test if this still an issue with latest `2016.8` and `2017.7`.

**Comment by dmurphy18** [comment]
@vutny If you could also include Salt 20`8.3.0 too, since that is the latest release, it would be great.

**Comment by vutny** [comment]
@dmurphy18 I had no time to re-test this, but I assume everything should work just fine. If I would found that it is not, I will reopen the issue. Thank you.
