### ISSUE TITLE
repo.saltstack.com Installation Path for Amazon Linux 2

### ISSUE THREAD

**Issue by grichmond-salt** [saltstack/salt-pack#578]
Team,

A user reported a problem with following the guide at repo.saltstack.com for Amazon Linux.

The user is using Amazon Linux 2.  The rpm to install the repo creates a repo path of:
`https://repo.saltstack.com/yum/amazon/2/x86_64/latest/repodata/repomd.xml`

@dmurphy18 confirms that installation of the RHEL 7 packages works on Amazon Linux 2, so a symlink for the path may be a solution.

**Comment by dmurphy18** [comment]
Fixed with PR https://github.com/saltstack/salt-pack-extras/pull/138.  The upcoming point releases for 2017.7.8, 2018.3.3 are supported on Python 2.

@grichmond-salt Is the scheduled point releases soon enough, end of August sufficiently soon ?

**Comment by dmurphy18** [comment]
Awaiting testing and release

**Comment by grichmond-salt** [comment]
@dmurphy18:
Apologies for missing the question above...
Yes, I think the point release is just fine.
