### ISSUE TITLE
salt-repo-2018.3-1.el7.noarch.rpm : warning Public key for PyYAML-3.11-1.el7.x86_64.rpm is not installed

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt-pack#622]
# Steps  to reproduce
Goto https://repo.saltstack.com/#rhel
Click "Pin to Major Version"

sudo yum install https://repo.saltstack.com/yum/redhat/salt-repo-2018.3-1.el7.noarch.rpm 

# Read

warning: /var/cache/yum/x86_64/7/salt-2018.3/packages/PyYAML-3.11-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID de57bfbe: NOKEY0 B/s | 561 kB  --:--:-- ETA
Public key for PyYAML-3.11-1.el7.x86_64.rpm is not installed

#

**Comment by dmurphy18** [comment]
fixed with https://github.com/saltstack/salt-pack-extras/pull/165
