### ISSUE TITLE
Correct spec files for RHEL 7 Salt to use correct python-futures

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#658]
Requires: python2-futures >= 2.0

should be:

Requires: python-futures >= 2.0

And rely on python2-futures from RHEL 7 base repo to have an alias to python-futures, it currently does

**Comment by anindyar** [comment]
Hey guys,

any eta for this fix?

**Comment by dmurphy18** [comment]
Appears to be no difference between CentOS and RHEL 7

root@localhost:~# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
root@localhost:~# yum list python*-futures
Loaded plugins: fastestmirror, langpacks
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Loading mirror speeds from cached hostfile
 * base: mirror.chpc.utah.edu
 * extras: mirror.chpc.utah.edu

 * updates: mirror.chpc.utah.edu
Installed Packages
python2-futures.noarch                                                                   3.1.1-5.el7                                                                   @base      
Available Packages
python-futures.noarch                                                                    3.0.3-1.el7                                                                   salt-latest
root@localhost:~# 

[root@ip-10-200-19-243 ec2-user]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[root@ip-10-200-19-243 ec2-user]# yum list python*-futures
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Available Packages
python2-futures.noarch                                                        3.1.1-5.el7                                                         rhui-REGION-rhel-server-releases
[root@ip-10-200-19-243 ec2-user]#

Updating spec files and the next point release should require python-futures
