### ISSUE TITLE
Packages for Debian 10

### ISSUE THREAD

**Issue by sim0nx** [saltstack/salt-pack#690]
Hi,
With Debian 10 around the corner, could you please add support for this new release ?

**Comment by jerrykan** [comment]
Is there any sort of time frame for official support of Debian10? I'm currently using work-arounds to use the Debian 9/stretch repos to install the packages on Debian10, but it would be nice to remove these hacks.

**Comment by bbinet** [comment]
@dmurphy18 Will the salt 2019.2.1 release be available for the current stable version of Debian (Buster, Debian 10) ?

**Comment by bryceml** [comment]
there are python3 debian 10 packages now. Closing.
