### ISSUE TITLE
Add pygit2 0.20.3, libgit2 0.20.0 to Ubuntu 12.04/14.04 LTS repos

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt-pack#70]
Debian does not package this at all, so it needs to go in for both wheezy and jessie.

Ubuntu 16.04 LTS ships with pygit 0.24.0 and libgit2 0.24.1 (package name is actually ``libgit2-24`` in 16.04 LTS) in the **universe** repo, so there is no need to provide it.

**Comment by terminalmage** [comment]
The reason for using these specific versions is to avoid the dependency on python-cffi added in pygit2 0.21.0, which would in turn require an update of libffi, a library on which many other applications depend. Updating libffi is not advisable, so 0.20.3 is our only option on these releases.

Looping in @snergster as this is relevant to his workflow.

**Comment by dmurphy18** [comment]
https://github.com/saltstack/salt-pack/issues/78

need to pull in locally built libgit2-dev as a dependency to allow for git2.h header file when building python-pygti2

**Comment by dmurphy18** [comment]
Got pulling in of locally built dependencies.

However, having issues with a specific version if later version exists, e.g. using locally build libgit2-dev 0.20.0 when libgit2-dev 0.21.0 exists from jessie main. Pinning appears to have issue with origin and local file system, even after apt-get --allow-unauthenticated update

**Comment by dmurphy18** [comment]
Closing this as not proceeding with this, due to not a required dependency.

**Comment by Snergster** [comment]
Oh that's awesome. You mean there is a different library that you can use for ssh git or gitfs user and password combinations?   That's great. Please add that in since it certainly seems that gitfs certainly seems like a pretty fundamental tool for salt use

**Comment by dmurphy18** [comment]
@Snergster This does not change the current situation for use of pygit2 and libgit2, where a user can install using pip or other means. This task looked at possibly supplying those packages from repo.saltstack.com as a convenience to users, however it was determined not to proceed with the task due to other time constraints and commitments.
