### ISSUE TITLE
Update python-msgpack support on Redhat 7 to v0.5.6

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#700]
Need to update python-msgpack support on Python 2 Redhat 7 to v0.5.6, similar to that on Python 3ot

Note that this has been a requirement in Salt requirements/base.txt since May 9, 2018 due to msgpack-python having been deprecated.

**Comment by dmurphy18** [comment]
https://github.com/saltstack/salt-pack/pull/701

**Comment by dmurphy18** [comment]
PR merged

**Comment by revmehul** [comment]
Thanks much. 🙏
