### ISSUE TITLE
Add support for debian armhf architecture

### ISSUE THREAD

**Issue by bbinet** [saltstack/salt-pack#72]
So that salt-minion can be installed on arm devices such as a raspberry pi.

**Comment by dmurphy18** [comment]
@bbinet Which armhf architecture, v7 ? or v8 ?, both ?

**Comment by bbinet** [comment]
I would say v7 so that it also works en v8.

**Comment by bbinet** [comment]
Ideally arm v6 would also be great so that it works on raspberry pi 1 devices.

**Comment by dmurphy18** [comment]
@bbinet wondering if worth the split out of v6, v7 and v8 support since I love my Pi 1, but would like to get Pi 3 in 64 bit mode (noting 32-bit at moment for Rasbian)

**Comment by bbinet** [comment]
I think it does not makes much sense to support for arm 64bit until Raspbian also adds support for it.

It is ok to split out v6, v7, and v8, but it means more work, isn't it? Note that if we add support for arm v6, it will also work for v7 and v8 architectures.

Are you planning to add support for armhf architecture for the 2016.3 release? It would be great and I would volunteer to test the packages on my rpi1 and rpi2 devices.
