### ISSUE TITLE
Signing using SHA1 is deemed insecure by Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by LordMike** [saltstack/salt-pack#76]
Hi,

I did an apt update on a new Ubuntu 16.04 with `deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main` and received the following output:

    W: http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/dists/trusty/InRelease: 
    Signature by key 754A1A7AE731F165D5E6D4BD0E08A149DE57BFBE uses weak digest algorithm (SHA1)

I then found this page: https://wiki.debian.org/Teams/Apt/Sha1Removal, as well as other references stating that Canonical moved a few big changes up as 16.04 will be supported for 5 years, so they'd better get them in.

Salt should sign using `SHA256` or better, it seems.

**Comment by dmurphy18** [comment]
@LordMike Thanks for your observation on the demise of SHA-1. I will take that into account when building SaltStack's Ubuntu 16.04 LTS release.

**Comment by dmurphy18** [comment]
Appears not needed, already adding sha-256

**Comment by jv2222** [comment]
I'm a bit stuck... Any ideas how I can get past this?

salt 2016.11.5 (Carbon)
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-1013-aws x86_64)

root@pla-live-salt:/home/ubuntu# apt-get update
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]      
Hit:5 http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty InRelease
Hit:6 http://ppa.launchpad.net/webupd8team/y-ppa-manager/ubuntu xenial InRelease
Fetched 102 kB in 0s (130 kB/s)                    
Reading package lists... Done
W: http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/dists/trusty/InRelease: Signature by key 754A1A7AE731F165D5E6D4BD0E08A149DE57BFBE uses weak digest algorithm (SHA1)

**Comment by dmurphy18** [comment]
@jv2222 Please check your /etc/apt/sources.lst file for the correct version of Ubuntu.  It would appear from the lines above that you are trying to load Ubuntu 14.04 instead of Ubuntu 16.04

I would have expected Hit:5 to have been as follows, and not contain trusty :

http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main

Please recheck your /etc/apt/sources.lst against the instructions in http://repo.saltstack.com/#ubuntu

You should be attempting to load for 'xenial' and not 'trusty' with Ubuntu 16.04 LTS.

**Comment by jv2222** [comment]
@dmurphy18 Yes you are correct! 

I was able to move past this particular issue and I wanted to come back here and let you know but then for some reason I couldn't find the ticket. 

Anyway, now I got an email alert and just want to let you know not to worry about my question.

Thanks!
